apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadpzcq4659-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadpzcq4659-tenant-component
    app.kubernetes.io/part-of: loadpzcq4659-tenant-app
  name: loadpzcq4659-tenant-component
  namespace: loadpzcq4659-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadpzcq4659-tenant-component
    weight: null
status: {}
